[package]
name = "stylish"
version = "0.1.0"
authors = ["Wim Looman <crates.stylish@nemo157.com>"]
edition = "2018"

[workspace]

[dependencies]
askama_escape = "0.3.0"
stack_dst = "0.6.0"
stylish-macros = { path = "macros" }
