[package]
name = "stylish"
version = "0.1.0"
authors = ["Wim Looman <crates.stylish@nemo157.com>"]
edition = "2018"

[workspace]

[dependencies]
stylish-macros = { version = "0.1.0", path = "macros" }
stylish-core = { version = "0.1.0", path = "core" }
stylish-html = { version = "0.1.0", path = "html" }
stylish-ansi = { version = "0.1.0", path = "ansi" }
stylish-plain = { version = "0.1.0", path = "plain" }
