warn = [
  "missing_copy_implementations",
  "missing_debug_implementations",
  "missing_docs",
  "trivial_casts",
  "trivial_numeric_casts",
  "unused_extern_crates",
  "unused_import_braces",
  "variant_size_differences",
  "clippy::allow_attributes_without_reason",
]
