[package]
name = "stylish-ansi"
version = "0.1.0"
authors = ["Wim Looman <crates.stylish@nemo157.com>"]
edition = "2018"

[dependencies]
stylish-core = { version = "0.1.0", path = "../core" }
stylish-macros = { version = "0.1.0", path = "../macros" }
