[package]
name = "stylish-html"
version = "0.1.0"
authors = ["Wim Looman <crates.stylish@nemo157.com>"]
edition = "2018"

[dependencies]
askama_escape.version = "0.3.0"
stylish-core.path = "../core"
stylish-core.version = "0.1.0"
