name: docs

env:
  RUST_BACKTRACE: 1

jobs:
  docsrs:
    name: cargo +nightly doc --cfg docsrs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - uses: actions-rs/cargo@v1
      env:
        RUSTDOCFLAGS: --cfg=docsrs -Dwarnings
      with:
        command: doc
        toolchain: nightly
        args: --no-deps --workspace --all-features --locked

on:
  push:
    branches: [staging, trying]
