name: lint

env:
  RUST_BACKTRACE: 1

jobs:
  # TODO: needs to use nightly currently for doc-comment formatting
  fmt:
    name: cargo +nightly fmt --check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
        components: rustfmt
    - uses: actions-rs/cargo@v1
      with:
        toolchain: nightly
        command: fmt
        args: -- --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with: { components: clippy }
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace --all-targets --all-features --locked -- -D warnings

on:
  push:
    branches: [staging, trying]
  pull_request:
    branches: [prīmum]
