name: nightly

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    name: cargo +nightly test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - uses: actions-rs/cargo@v1
      with:
        toolchain: nightly
        command: test
        args: --workspace --locked --all-features

  proc-macro-expand:
    name: cargo +nightly test --cfg stylish_proc_macro_expand
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
    - uses: actions-rs/cargo@v1
      env:
        RUSTFLAGS: --cfg stylish_proc_macro_expand
      with:
        toolchain: nightly
        command: test
        args: --workspace --locked --all-features

  fmt:
    name: cargo +nightly fmt --check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
        components: rustfmt
    - uses: actions-rs/cargo@v1
      with:
        toolchain: nightly
        command: fmt
        args: -- --check

  clippy:
    name: cargo +nightly clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
        components: clippy
    - uses: actions-rs/cargo@v1
      with:
        toolchain: nightly
        command: clippy
        args: --workspace --all-targets --all-features --locked -- -D warnings

  create-issue:
    name: create issue
    runs-on: ubuntu-latest
    if: failure()
    needs: [test, proc-macro-expand, fmt, clippy]
    steps:
    - uses: actions/checkout@v2
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        RUN: ${{ github.run_id }}
      with:
        update_existing: true
        filename: .github/nightly-issue.md

  close-issue:
    name: close issue
    runs-on: ubuntu-latest
    needs: [test, proc-macro-expand, fmt, clippy]
    steps:
    - uses: lee-dohm/close-matching-issues@v2
      with:
        query: 'is:open label:nightly'
        token: ${{ secrets.GITHUB_TOKEN }}

on:
  schedule:
  - cron: '0 2 * * *'
  push:
    branches: [prīmum]
