jobs:
  pull_request:
    uses: Nullus157/.github/.github/workflows/pull_request.yml@main
    with:
      fmt-toolchain: nightly
  staging:
    uses: Nullus157/.github/.github/workflows/staging.yml@main
    with:
      skip-features: _tests
  success:
    runs-on: ubuntu-latest
    needs: [pull_request, staging]
    if: ${{ always() }}
    steps:
    - if: ${{ contains(needs.*.result, 'failure')  }}
      run: exit 1
    - if: ${{ contains(needs.*.result, 'cancelled')  }}
      run: exit 1
    - if: ${{ contains(needs.*.result, 'skipped')  }}
      run: exit 1

on:
  merge_group:
    type: [checks_requested]
